### ISSUE TITLE
"Visual" samples of some components are truncated vertically.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/design-system#104]
The iframe that is generated by the ComponentPreview component did not initially set a height.  It has been updated to allow this to be set as a property on the component in the markdown file, as below, and the affected samples need to be updated to take advantage of this.

<component-preview path="components/primary_button/sample.html" height="70px"> </component-preview>

**Comment by sheaphillips** [comment]
@orinevares please see https://github.com/bcgov/design-system/pull/105

**Comment by orinevares** [comment]
@sheaphillips ok great, thanks for the info. I'll get into this today.
