### ISSUE TITLE
Microcopy aound the Design System's UI 

### ISSUE THREAD

**Issue by michaeltangbcgov** [bcgov/design-system#116]
Evaluation Criteria
•    Impact on citizens: The component would make it easier for Developers to create UI for Users that conforms to Government Usability standards. 
•    Usage: Once the component is created it could be the standard for future components. 
•    Volume of Requests: The component has been frequently requested by the community.
## What
> There should be samples in the Design System for wording used on Digital applications that are reusable and current.  

## Why
> Explain why you think this should be added to the BC Gov Design System.
> A Microcopy sample can standardize wording surrounding government digital experiences leading to higher completion rates from applications.  
> - What evidence do you have that it's needed by multiple services across government?
There is a whole industry spawning out of the Microcopy field that is splitting from UX Designers.
Tech companies like Air BnB spend millions on getting the correct wording right for applications that Users trust. 

## Anything else
> Include links to any examples, research or code to support your proposal, if available.
https://www.microcopyinspirations.com/
https://blog.prototypr.io/building-better-product-with-ux-writing-775b205806ae

**Comment by dlevineBC** [comment]
Hey @michaeltangbcgov this has been added to our backlog for future work. Do you have any specific examples from your work where there is a need for microcopy?
