### ISSUE TITLE
Font Family in Header Component (or in any visual component)

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/design-system#13]
There is a css property for `font-family: 'PT Sans` in https://github.com/bcgov/design-system/blob/master/components/header/README.md

This can be found in the CSS code example `header h1 { ...`
There are two things that we should take a look into with:
1. Ideally, we would have a global style set on the `body` which sets things like the `font-family`. That way the font-family would cascade down. This begs having a discussion on basic global stylesheet. That or, discussing components for typeography and making 'visual' components indifferent to typeography
2. Whenever using custom fonts, would should always have a fallback font in a similar style. I'd recommend `font-family: 'PT Sans', sans-serif`;

**Comment by orinevares** [comment]
That makes sense, I am still figuring out the nuances behind the security implications of using an open source font over a licensed adobe font.

**Comment by bl-smith** [comment]
Yes, that makes sense to me as well. For the next sprint, I think we should tackle "typography" as a component to add to the design system, and this would allow us to create the global stylesheet which could be applied to other components - similar to how the US Design System has it listed: https://designsystem.digital.gov/components/typography/ . What do you think?

**Comment by patricksimonian** [comment]
As far as having typography components, I think that's a great idea. It may give you guys the freedom to allow for more than just one font for different use cases too (if needed). The global style sheet would definitely take some work. I think one think you'd want to avoid is HAVING to include that global stylesheet for things to work. In some front end frameworks they may have a *preferred* way of compiling global styles. Being able to build that on one's own using all of the components (including typeography) ones would be a really great start

**Comment by patricksimonian** [comment]
What would your concerns be on security for a CDN'd fonts? These are being loaded from google fonts api which i believe is fairly secure. The only possible draw back i for see is the *slightest* of possibility that the service that sends the font files to your browser goes down. In any case having backup font families as mentioned in Item 2 of my original post would rectify that.
