### ISSUE TITLE
SVG Images not rendering in the Design System

### ISSUE THREAD

**Issue by orinevares** [bcgov/design-system#130]
- Specifically in the iframe examples of the header, navbar and beta badge components
- Icons on the icon page
- Colours on the colour palette

**Comment by patricksimonian** [comment]
can't remember where we landed on this. Any updates?

**Comment by dlevineBC** [comment]
I believe @orinevares just put the entire svg in the code as a short term solution.

However for the svg icons that are broken on icon page, we should just use the font awesome <i></i> rather than try and use the svg . files. I tried putting that in but it wasn't rendering. Are we using the fontawesome CDN on devhub?

The colour palette isn't affected by svgs

**Comment by patricksimonian** [comment]
Agreed, we are not currently using the CDN but rather a fontawesome package. The font awesome package does preload the stylesheet though so i don't think you should need it. 

You should be able to use the basic fontawesome implementation which is using `<i>` html tags

eg: `<i class="fa fa-book" aria-hidden="true"></i>`

**Comment by orinevares** [comment]
The SVG images in the iframes are referencing the SVG on the actual DevHub website. The embedded SVG code was not working. This was done as a temporary solution.

I can try and put in the basic fontawesome implementation and see what happens when I make a few other edits today.

**Comment by orinevares** [comment]
@patricksimonian I tried putting in the <i> tags for each icon but they also didn't render properly. Any further ideas? Also might be best to discuss with others here while you have your surgery.

**Comment by patricksimonian** [comment]
Hmm i'll have to take a look tomorrow morning and see whatsup

**Comment by orinevares** [comment]
This was left with us inputting 40px png files of the icons as a temporary fix while further work is needed on how to properly render svg files.
