### ISSUE TITLE
Radio Button, Content Edits

### ISSUE THREAD

**Issue by kaitlyn-rosenburg** [bcgov/design-system#133]
![screen shot 2019-02-26 at 1 49 32 pm](https://user-images.githubusercontent.com/48034224/53449879-c3f2e600-39cf-11e9-9e3d-45d2ae8123de.png)

Suggested Change:

Use This When

- A user must select one option from a list.

Don't Use This When

- A user can select more than one option from a list. In this case, use a checkbox.

![screen shot 2019-02-26 at 2 10 36 pm](https://user-images.githubusercontent.com/48034224/53450106-51ced100-39d0-11e9-8e2d-0116cc363c91.png)

Suggested Change:

Design Guidance

- Once a user has selected an option, they cannot return to having no options selected. If applicable, include a "None of the above" or "I don't know" option.

- Do not assume a user will know how many options they can select. If needed, include a hint like "Select one option."

- It can be helpful to order the options based on user needs, like placing the most likely response at the top.

- Options should always be listed vertically.

**Comment by dlevineBC** [comment]
@kaitlyn-rosenburg 
* A user must select one option from a list.

This wording implies that a user has to selection an option, not that only one is able to be selected. The suggested wording could apply to a checkbox. We are suggesting this instead:

* A user can only select one option from a list.

**Comment by kaitlyn-rosenburg** [comment]
Good suggestion, works for me
