### ISSUE TITLE
Adjust DevHub Typography and configure Typography.js

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#142]
After the implementation of typography.js the typography across the devhub platform was changed. 

To do:
- Figure out how typography.js works to customize site wide typography and implement these changes on Devhub/Design System
- Work with @sheaphillips to figure out how this configuration works

This configuration would ultimately be the typography package available to product teams as one option.

Definition of done: 
- Typography.js is built to reflect the typography guidance outlined on the design system
- Typography across DevHub is consistent

**Comment by dlevineBC** [comment]
@orinevares Can you make sure any reference to google api for Noto is replaced with the font files?

**Comment by orinevares** [comment]
Yes, I was reading and seems like this is the way to embed font file locally.

https://stackoverflow.com/questions/28279989/multiple-font-weights-one-font-face-query

It seems to get messy and repetitive if we were to include this on every CSS sheet for every component so I'm thinking of doing one CSS file for the all the files and including it on the typography page while deleting all the google references. Thoughts? @dlevineBC

**Comment by dlevineBC** [comment]
Is this because the iframes can't reference files outside of the frame? Can the font just be called from the typography.js instance?

**Comment by orinevares** [comment]
I'll have to follow up with Shea on this. He's away until Monday. I'm also thinking how to present the locally hosted fonts on the documentation code for users of the design system to see.

**Comment by orinevares** [comment]
Hi everyone,

I updated the typography.js file to include the proper typographic scale. (accidentally committed to master - sorry Patrick). The changes are not reflected on DevHub and after looking into this briefly with Shea last week it seems like there is some more granular CSS that is overwriting the typography.js specifications. I can start an initial look into possible sources of the setting being overwritten but @patricksimonian  if you know exactly where this might be let me know.
