### ISSUE TITLE
Disabled Inputs - Checkbox

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#149]
## What
> Styling and guidance for checkboxes. This is in response to #118 

# Why
> Checkboxes can be disabled when the option is not available, until a further action is completed.

## Anything else
> Guidance should be included as to when this is and is not appropriate to use

**Comment by TWuolle2016** [comment]
Any update on this ?

**Comment by dlevineBC** [comment]
We don't have any guidance on this component yet. Please utilize the checkbox component and you are free to design the disabled state taking into consideration contrast requirements for accessibility. For any disabled component it should be clear to the user why something is disabled or if it makes more sense to simply not show the component (this depends on your context). When you implement this please report back on any usability issues or other research findings that others in the community would find beneficial and could be included for future guidance.
