### ISSUE TITLE
Help Text

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#152]
## What
> Additional information with a text input that clarifies what is required to input

## Why
> Sometimes a text input or text area requires an example or to show what a valid response might be (ie. postal code format). This helps prevent user errors by clearly telling users what is required.

**Comment by patricksimonian** [comment]
I'd take a look at material ui for some inspiration on this. They do a great job handling helper text/validation text

**Comment by dlevineBC** [comment]
Hint text
Use hint for help that’s relevant to the majority of users, like how their information will be used, or where to find it.

**Comment by dlevineBC** [comment]
Hint text (Australia)
Hint text can be used to provide more context that will help the user successfully complete the form field.

**Comment by dlevineBC** [comment]
The colour grey meets good contrast ratio  #70777C, but is still light enough to feel like a piece of secondary text.

**Comment by dlevineBC** [comment]
Updated the card from Hint Text to Help Text as this is how we describe it in the guidance and seems to be the more common usage term

**Comment by dlevineBC** [comment]
Accessibility guidance for help text via Bootstrap: 
"Associating help text with form controls:
Help text should be explicitly associated with the form control it relates to using the `aria-describedby` attribute. This will ensure that assistive technologies—such as screen readers—will announce this help text when the user focuses or enters the control."
https://getbootstrap.com/docs/4.0/components/forms/#help-text

**Comment by dlevineBC** [comment]
Australia uses a `<span>` `<span class="au-hint-text" id="email-hint">We will only use this to respond to your query</span>`
UK also uses a span with custom class
