### ISSUE TITLE
Buttons on Dark Backgrounds

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#153]
## What
> Primary and secondary buttons are sometimes used on a dark background. Expand the button design to accommodate this use case.

## Why
> Buttons are used in the header of the websites that use the same colour as the primary button colour. We need a variation of the primary button and potentially the secondary button for this use.

## Anything else
> BCeID uses https://www.bceid.ca/ white and outline button design

**Comment by orinevares** [comment]
Some initial ideas for dark background buttons.

<img width="955" alt="Screen Shot 2019-04-24 at 1 20 27 PM" src="https://user-images.githubusercontent.com/43620986/56691040-c7cf7b80-6693-11e9-9f8e-2f31eb69b43a.png">

**Comment by orinevares** [comment]
<img width="959" alt="Screen Shot 2019-04-24 at 1 22 28 PM" src="https://user-images.githubusercontent.com/43620986/56691133-07966300-6694-11e9-92a8-02401a0b4e4f.png">

**Comment by orinevares** [comment]
<img width="957" alt="Screen Shot 2019-04-24 at 2 01 05 PM" src="https://user-images.githubusercontent.com/43620986/56693488-6d391e00-6699-11e9-8af4-2c4d1e4394c6.png">
<img width="500" alt="Screen Shot 2019-04-24 at 2 01 00 PM" src="https://user-images.githubusercontent.com/43620986/56693489-6d391e00-6699-11e9-95e4-a27fa0108d88.png">
