### ISSUE TITLE
Dropdown List

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#157]
New component in forms for dropdown list of items to select

**Comment by orinevares** [comment]
After briefly reading on dropdown lists it seems like its the​ last resort for UI due to the many difficulties people face using this style of list. Let's discuss the importance of having this available as opposed to pushing people to use other means of form inputs.

**Comment by dlevineBC** [comment]
I know the UK guidance advises/advised for awhile to stay away from using them, though they did eventually add it, called the "select" component. I see it like the disabled button, where we should provide guidance on more appropriate components to use instead of a dropdown, but they will inevitably be used so we should provide design and guidance on how to do it well and make it visually aligned.

**Comment by orinevares** [comment]
Ok I'll get going on this now.

**Comment by orinevares** [comment]
UK Design System

![Screen Shot 2019-04-03 at 12.10.47 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/a51776ac-7e64-465c-bc4e-4ad13f0b2bd6)

![Screen Shot 2019-04-03 at 12.10.43 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/d61993e2-8f26-42eb-960e-f80d56d398bc)

**Comment by orinevares** [comment]
US Design System

![Screen Shot 2019-04-03 at 12.10.30 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/d3e6e7d5-0c3c-4e3e-a4cb-161a49a0dcfd)![Screen Shot 2019-04-03 at 12.10.35 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/d74ba737-4bf5-46a0-b67a-eb28f5c13782)

**Comment by orinevares** [comment]
Australian Design System

![Screen Shot 2019-04-03 at 12.12.45 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/20947e8f-31a0-4b32-8982-b8b66db9b7db)

![Screen Shot 2019-04-03 at 12.12.50 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/267f041a-49c4-4953-8ef2-2861ba454485)

**Comment by orinevares** [comment]
BC Gov ACCB Estimator

![Screen Shot 2019-04-03 at 12.16.58 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/c7389cc9-036b-479a-98c0-ad1bb59cc5e0)

![Screen Shot 2019-04-03 at 12.17.03 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/77f8da3d-821f-4b69-80f4-918ad5d1bd4d)

**Comment by orinevares** [comment]
First design prototype and rationale

![Screen Shot 2019-04-03 at 1.57.31 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/1f4f840d-ce49-443e-b10b-0ad3eea450ea)

**Comment by dlevineBC** [comment]
Few comments: I wouldn't say these are "ghost style" because there would be a white background. We wouldn't want there to be a transparent background. 
I don't think drop downs have a hover state like a button, so there would be no underline.
