### ISSUE TITLE
Alert Banner

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#172]
Create design system component for:

-Alerts
-Warning
-Information

**Comment by orinevares** [comment]
![Screen Shot 2019-04-03 at 10.48.48 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/78ff86a7-d574-4606-94bd-772858bfd0e9)![Screen Shot 2019-04-03 at 10.48.59 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/f2a08179-7e4a-4072-afeb-9ff120c4c14f)![Screen Shot 2019-04-03 at 10.49.12 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/b051a2a5-21d5-419f-b288-5787ac445a83)

**Comment by orinevares** [comment]
![Screen Shot 2019-04-03 at 11.03.54 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/890e29f3-698e-4751-b06d-af3f673ad931)

**Comment by orinevares** [comment]
US Design System

![Screen Shot 2019-04-03 at 11.04.19 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/c80f2d4f-586d-4c99-b7d5-2256bef51798)

**Comment by orinevares** [comment]
Australia Design System

![Screen Shot 2019-04-03 at 11.04.56 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/0a25cb88-0791-48e2-a09c-8be24b52762f)![Screen Shot 2019-04-03 at 11.04.51 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/d189aa16-1a7b-4413-9d1a-18e6f036564a)![Screen Shot 2019-04-03 at 11.04.44 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/1db751f7-b8cf-473a-a40c-c76fcd26c812)![Screen Shot 2019-04-03 at 11.04.38 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/f8822316-920e-4775-9d55-c9b5c44862bf)

**Comment by orinevares** [comment]
![Screen Shot 2019-04-03 at 11.07.15 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/4f5465f2-1861-4ce3-8ffa-dcea282058a5)

**Comment by orinevares** [comment]
![Screen Shot 2019-04-03 at 11.08.42 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/233dd458-dec2-4aed-90ed-e20ef5a98c06)

**Comment by orinevares** [comment]
![Screen Shot 2019-04-03 at 11.09.14 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/6ab45e22-5160-47d0-a9a2-75012e59f59b)

**Comment by orinevares** [comment]
![Screen Shot 2019-04-03 at 11.11.11 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/22e4be69-93da-4ee5-bd47-536ede384afb)

**Comment by orinevares** [comment]
First prototypes for BC Gov.

![Screen Shot 2019-04-09 at 11.42.28 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/768a0869-a1e7-4283-9cda-43afef743793)

**Comment by dlevineBC** [comment]
Initial comments:
- Would remove the exclamation mark
- Info should spell out Information
- Icons could probably be sized to the same height as the title
- I'm assuming the warning colour is the primary BC Gold colour? I'm wondering if it makes sense to use a primary branding colour for warning or if we should use a more distinct orange

**Comment by orinevares** [comment]
@dlevineBC ok working on the edits now. The warning colour is actually f3bd48 pulled from the approved secondary palette on the developers guide.

https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/web-content-development-guides/developers-guide/css-elements

**Comment by orinevares** [comment]
Updated prototype.

- I actually prefer the exclamation marks on Success, Warning, and Error. Information should be as is.
- Also prefer the larger icons and maybe centering them with the height of the banner.
<img width="867" alt="Screen Shot 2019-04-09 at 12 57 01 PM" src="https://user-images.githubusercontent.com/43620986/55831002-00355e00-5ac7-11e9-80cf-2c518f7abb5a.png">

**Comment by dlevineBC** [comment]
Here is what I think of exclamation points as explained by someone else: 
"The trouble is, words are hard work. Even professional writers struggle to find the right words when we want to persuade, to energize, to goad others into action. So it's not too surprising that we often fall back on using punctuation to lend us a hand. 

But it's a trap. And exclamation marks are the biggest trap of them all. Overused all over the web, these hardworking little symbols are the smiley faces of the punctuation world. We rely on them far too heavily when what we really need to do is go back to our words and try to make them convey more precisely what we're trying to say.

**Don't ask punctuation to do a word's job**"

For this particular context we are conveying information through colour, icon, and text. The punctuation is an attempt to add tone, but at the same time attempting to apply different tones using the same mark.

If we haven't effectively communicated that there is an error without using an exclamation mark then we've done a bad job.

**Comment by dlevineBC** [comment]
The spacing to the left and right will need to be adjusted to accommodate a smaller icon size. 

For the background colour I'd say it's safer to use a lighter tint version of the colour rather than rely on opacity just because we lose control over the colour when using opacity so we could run into issues with colour contrast. If this banner was on a light grey background the background of the alert would would appear darker. It would also give us a defined colour to include for the colour palette

**Comment by orinevares** [comment]
Ok good points! How do you feel about keeping the icon size larger as with the original prototype post?

**Comment by orinevares** [comment]
![Screen Shot 2019-04-09 at 2.53.24 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/9575a3ce-1e9e-474e-b03f-0528d1ac403e)

**Comment by dlevineBC** [comment]
An issue with middle alignment is if you have a lot of body text it can feel like it's floating. Anchoring it so it's top aligned to the title would feel more visually stable

**Comment by orinevares** [comment]
Ok the top alignment also eases the transition from the icon to the associated text which is nice.

**Comment by orinevares** [comment]
<img width="865" alt="Screen Shot 2019-04-09 at 4 18 18 PM" src="https://user-images.githubusercontent.com/43620986/55841203-1e10bc00-5ae3-11e9-9578-3eb995bc4c0a.png">

**Comment by dlevineBC** [comment]
What are your thoughts on using "Information" vs "Important"? One of the reason I don't think saying "Information" is a useful title is because all the alerts are information, so it doesn't provide anything additional to give the user an idea of what the content would be. It also leaves the use of it much more open for people to mis-use. I think the way Australia has used the term "Important" is more effective.

**Comment by dlevineBC** [comment]
For the size of the icons, they still feel too big. Right how it seems to be based just on having equal spacing left and right, but it's not proportional to the text. Looking at the size of the USDS alerts the icons are sized to reach the top line of the paragraph text. This anchors the icon because they are aligned to something. At a minimum I would resize it to that.

**Comment by orinevares** [comment]
![Screen Shot 2019-04-10 at 1.55.16 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/e3c9217f-c1b0-44c8-a0b8-f756c4b808ec)
