### ISSUE TITLE
Information Collection Notice

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#181]
Evaluation Criteria
•    Impact on citizens: Citizens are provided information on how their information is being collected
•    Usage: Every service collecting personal information needs this

## What
A statement indicating the authority to collection information and how the information will be used.

## Why
As defined in a forms standards document:
**Personal Information Proviso Section**
If the form is used to collect personal information it
must contain a Personal Information proviso. The proviso
must specify the authority or legislation for collecting the
information, must specify how the information will be
used, and must identify a contact position and phone
number where detailed information about the collection,
use and disclosure of the data can be obtained

## Anything else
> Include links to any examples, research or code to support your proposal, if available.
Forms standards: https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/service-experience-digital-delivery/forms_management_standards.pdf 
Example from FOI application
<img width="1178" alt="privacy-notice" src="https://user-images.githubusercontent.com/29607430/55441874-2c9a2900-5561-11e9-9a01-bd05a55bfde2.png">

**Comment by davidcusack** [comment]
Hi @dlevineBC, is this still in development? I just spoke at the MPO forum trying to get some support to get some guidelines set for collection notices.

It would be nice to have some direction on: 

- Placement and maybe different recommendations depending on the type of collection. A survey might need to have it up front, where a collection of less sensitive information you might not need until the end
- Plain language and content design
- Links to the specific parts of the act
- Consistent application/interpretation of the laws across all ministries
