### ISSUE TITLE
Side Info Box

### ISSUE THREAD

**Issue by orinevares** [bcgov/design-system#184]
![Screen Shot 2019-04-03 at 10.43.56 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/b470117c-b603-4d5d-ae45-dfe883f721c6)

**Comment by dlevineBC** [comment]
<img width="1212" alt="divorce" src="https://user-images.githubusercontent.com/29607430/55576891-27ef8500-56c7-11e9-821a-b012d399f792.png">

**Comment by dlevineBC** [comment]
<img width="1134" alt="pharmacare" src="https://user-images.githubusercontent.com/29607430/55576904-3178ed00-56c7-11e9-8873-c4534115ae2f.png">
<img width="1086" alt="pharmacare2" src="https://user-images.githubusercontent.com/29607430/55576905-3178ed00-56c7-11e9-91dd-9ccda19c3d16.png">
<img width="1098" alt="pharmacare3" src="https://user-images.githubusercontent.com/29607430/55576906-3178ed00-56c7-11e9-80f8-48cf64610eae.png">
