### ISSUE TITLE
Date Input Component

### ISSUE THREAD

**Issue by orinevares** [bcgov/design-system#188]
Date range input example

![Screen Shot 2019-04-03 at 10.49.12 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/e1e6cb3a-bfab-4367-8c65-702ee809a2cb)

More specific input field on FOI Application Form

![Screen Shot 2019-04-03 at 10.50.57 AM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/0c5b607f-f5ce-49d0-9944-4524984bad44)

**Comment by victoriazou** [comment]
Should we use <input type="date"> or jQuery UI Datepicker or something else as a standard? We have at least one form using the jQuery version.

**Comment by orinevares** [comment]
<img width="772" alt="Screen Shot 2019-04-18 at 8 47 35 AM" src="https://user-images.githubusercontent.com/43620986/56373811-a6afec00-61b6-11e9-853c-5b5d03c1d69f.png">

**Comment by orinevares** [comment]
Hey Victoria!

Great point! Have a look at the date picker the UK Design system uses. This is a design we are leaning towards as opposed to a jQuery UI Datepicker for two main reasons.

UK Date Input -> https://design-system.service.gov.uk/components/date-input/

1. Typing in a known date is much faster than selecting it from a UI interface.
2. The typical jquery UI interfaces pose significant accessibility issues for those using keyboard navigation or screen readers

**Comment by victoriazou** [comment]
Here's a relevant caveat from the [US Design System](https://designsystem.digital.gov/components/form-controls/#date-input):

_If users are trying to schedule something, a calendar picker might make more sense. Be sure to also provide an option for text entry as well._

I agree the text fields work best for birthdays and other firm dates, but in the case of, say, event scheduling, it helps to see the contextual information. Could we explore something like Airbnb's [React datepicker](http://airbnb.io/react-dates)? It's keyboard friendly.

**Comment by orinevares** [comment]
Good point about the scheduling scenario and being able to the day of the week above numerical dates. We can definitely explore the Airbnb date picker more with this component.

**Comment by dlevineBC** [comment]
User research finding with the Bootstrap calendar picker for Ministry of Transportation application

"The main problem users have been finding while testing is that it is time-consuming and a bit confusing. Especially that the users are often birth dates which means not only picking month and day but also having to go quite a few years back."
