### ISSUE TITLE
Devhub Issue: Callout Visual Example not working in IE 11

### ISSUE THREAD

**Issue by GillianRuemkeDouglas** [bcgov/design-system#192]
> path: (do not delete) https://github.com/bcgov/design-system/blob/master/components/callout/callout.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Design-System/Callout

## Devhub Content Issue - 
Just shows: 'loading'

**Comment by sheaphillips** [comment]
Further experimentation has determined that there are more IE compatibility issues with DevHub & Design System than this one specific instance and it will take some effort to address them.

For now, we're going to close this issue and create a new more general issue for actioning in a future sprint.
