### ISSUE TITLE
Form Page

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#204]
Compile the component documentation found in 

- Help text 
- Inline error
- Form group

into one markdown file

DoD - content is compiled and added to the registry file

**Comment by patricksimonian** [comment]
missing front matter for this markdown file :)

**Comment by dlevineBC** [comment]
Issue identified from Transportation on labelling optional and required fields
--
The Gov standards for forms are built mostly for forms that have more required fields than optional. The recommendation is to label only the optional fields. E.g  Decommission date (optional). See below.
Many of the forms on this project are the opposite, more optional than required, but not always.
I am thinking of marking the outliers only, so that:
 
For forms where the input is mostly optional, we label the required fields
AND
For forms where the input is mostly required, we label the optional fields and put a line at the top that says “All fields are required unless labeled optional”
 
Alternatively, I could always label all the required fields, even if there are many on the form. This doesn’t happen very often so would be the more consistent approach.
 
The back and forth approach is [discussed here](https://www.formulate.com.au/blog/required-versus-optional-fields-new-standard/) noting that “backgrounder” or survey forms are different from other forms like registration where most fields are required.

**Comment by patricksimonian** [comment]
Would it lead to a poor ux if we stuck with only explictily labels 'optional' fields and providing helper messages for all fields when they don't validate correctly?

For example if a field is required and is submitted without being filled, a helper message appears by the field letting the user know it is required.

**Comment by dlevineBC** [comment]
Yeah we need to provide those helper messages for validation errors / missing information. We haven't put any guidance up yet for on forms messaging. To the point above, if you have form thats mostly optional fields it becomes really busy having every label having optional beside it.
