### ISSUE TITLE
Create DS inventory list of minimum components required 

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#208]
Review all the components we have created and create an inventory list that defines the remaining components we want to create for a minimum set of components required to have a "robust" set of DS components. 

Include alternate versions of components like disabled versions

**Comment by orinevares** [comment]
After looking through our component inventory and considering what is fundamental to make the design system useful here is a list of content organized by priority.

High Priority - To be done before socialization/marketing
- Variants of text input (email, phone number, date etc)
- Micro copy
- Labels
- Inline error

Low Priority - Can be done after socialization/marketing
- Lists
- Breadcrumbs
- Search
- Tabs

**Comment by orinevares** [comment]
@dlevineBC what are your thoughts on starting to push the socialization of the design system after we complete the high priority items?
