### ISSUE TITLE
Devhub Issue: Callout [short description here]

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/design-system#215]
> path: (do not delete) https://github.com/bcgov/design-system/blob/master/components/callout/callout.md
 > (do not delete) devhub page: https://devhub-static-dev-627-devhub-dev.pathfinder.gov.bc.ca/Design-System/Callout

## Devhub Content Issue

The callout component says it should be used for quotes with `<div>` tags but it may be more semantic to use the `<blockquote>` element
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote

Also the term call out to me seems like it could be confused with dialogue component (which is more of a modal like popup)

**Comment by dlevineBC** [comment]
The callout can be used for more than a quote ie. important pieces of information, so if we used the <blockquote> tag I don't think that would be great for semantic use. Probably better to explore ARIA as an indicator of message...

**Comment by patricksimonian** [comment]
well noted :) This issue can be closed if you like
