### ISSUE TITLE
Button hover switch opacity to background-color rgba or alternative colour

### ISSUE THREAD

**Issue by ShawnTurple** [bcgov/design-system#221]
## Which Component Has the Bug?
> Button

## Describe the bug
In the hover of the button, opacity 0.8 is used.
When using opacity, the entire element including text has opacity of 0.8.
Either use an alternative solid colour or use rgba on background.
ie...
``` background-color: rgba(0,51,102,0.8); ```

**Comment by orinevares** [comment]
Thank you for the contribution! I'll get to the edit now!
