### ISSUE TITLE
Button - change css to inline-block

### ISSUE THREAD

**Issue by ShawnTurple** [bcgov/design-system#222]
## Which Component Has the Bug?
> Button

## Describe the bug
Change the button to
```display: inline-block```

This is the convention that bootstrap uses, it works fine for a button element but not for a link ('a' element) ie ```<a href="myurl" class="BC-Gov-PrimaryButton" >My Button</a>```

**Comment by orinevares** [comment]
Thank you Shawn! This is super helpful!

**Comment by ty2k** [comment]
Cleaning up issues. I see this has been fixed in #223.
