### ISSUE TITLE
Detailed table component required 

### ISSUE THREAD

**Issue by rajpersram** [bcgov/design-system#225]
Evaluation Criteria
•    Impact on citizens: The component will enhance the functionality or usability of B.C. government websites or applications.
•    Usage: The component is commonly used or required and this need cannot be met with an existing component.
•    Volume of Requests: The component has been frequently requested by the community.
## What
> Give a brief description of the style, component or pattern you want to propose.

A styled table with headers, look of fixed rows and fixed columns.

## Why
> Explain why you think this should be added to the BC Gov Design System.
> We deal with data but currently there is not a component designers or developers can reference as the BC Gov standard.

> - What evidence do you have that it's needed by multiple services across government?
> - What evidence do you have that it meets the needs of the users of those services?
> - Have you checked that it doesn't already exist in the BC Gov Design System?

Yes. It was not found, searching for 'table' or 'tables'. 

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

Thanks!

**Comment by ShawnTurple** [comment]
As tables tend to have their faults, especially when it comes to responsive design, I have created a list element that mimics that of a table when it is desktop mode, but changes when in mobile.
Of course this isn't perfect, as the table headers are lost when in mobile, and have to be inserted into mobile.  Here is an example. [bcarts programs](https://www.bcartscouncil.ca/program/)
This uses flexbox and list elements.
