### ISSUE TITLE
Devhub Issue: Prototype with the Design System [short description here]

### ISSUE THREAD

**Issue by rajpersram** [bcgov/design-system#226]
> path: (do not delete) https://github.com/bcgov/design-system/blob/master/components/about/prototyping_tools.md
 > (do not delete) devhub page: undefined

## Devhub Content Issue
In terms of prototyping, mockups, etc, a group of 6-7 people who at the time (summer, 2018) made up the UX CoP did a two-week evaluation and relative comparison of 9 different UX Prototyping tools and based recommendations on the most practical, flexible and useful tools for typical needs in government. Sketch was not chosen because it is platform specific, leaving Windows users out. The top choice which was elected to be supported for use in the BC Gov was UXPin. The document, _UX Prototyping Comparison Sheet_, can be found in [this Sharepoint site](https://spc-csnr.gov.bc.ca/ux/Shared%20Documents/Forms/AllItems.aspx).

I recommend any functional components, wireframes, libraries be accessible via UXPin to maintain consistency. Furthermore, UXPin should be the recommended app for contractors who are working with the BC Gov.

**Comment by dlevineBC** [comment]
Thanks Raj, fair assessment on the lack of access for Windows users. One additional consideration we will be taking into account is which tool provide the ability to support design system components that can be updated and pushed out to users. Sketch had good support for this kind of shared model so that was one reason we were leaning towards that. As we make a decision we'll reference back to your analysis work and bring you into that conversation

**Comment by rajpersram** [comment]
Thanks Davis. Whatever the Service Design team chooses is a GDX matter, however, it’s in our collective interests since we have the user experience in common to come to one solution to reduce public costs and the siloing of ministries. The Component Library is meant for one purpose but a prototyping tool is more associated with a Style Guide and can have its own library matching a code-component version. The UX CoP’s original evaluation criteria which led to our comparison of 9 different software suites was to find ideally one prototyping and wireframing tool for quick turnaround of user experiencing research and testing. Coding flavours change on an annual basis whereas team-A will use the React library while team-B uses Angular; Team-C will use Java while team-d uses ASP. Those language choices will continually change with each year as they fall out of/into popularity.

CSS and HTML are foundations so it's great the current Design System components have those languages. A prototyping tool (ideally one) will also be a foundation where a BC Gov style library will need to, or at least ideally could, straddle both.

A component library be made and maintained in one prototyping tool but we sought to avoid a platform-specific tool as we’ve already seen a lot of pains from incompatibilities and ultimately a lot of time which means wasted money. Our shared aims are to speed up development and enable rapid prototyping. CGI, for example, has already switched to UXPin from Adobe XD to accommodate better collaboration with ongoing and upcoming gov projects.

UXPin has a customizable component library which can be shared between developers. In fact, I have been using the specifics from the BC Gov Design System for buttons, headers and so on in my own working prototypes, so that work has already begun. Here is a link showing generally how this works:

https://www.youtube.com/watch?v=B366HQzf4Ek&list=PLTQ1nMZTXSUUOSMKm_icOjaVosG17wbe4&index=4

Although Service Design and UX Design are not the same, we overlap in many areas, it would be ideal to establish common, platform agnostic tools. Looking forward to hearing GDX feedback on this.


Raj Persram | UX Designer, Information, Innovation and Technology Division | 250-818-5934
