### ISSUE TITLE
Devhub Issue: Colour Palette - Text Colour

### ISSUE THREAD

**Issue by davidcusack** [bcgov/design-system#237]
> path: (do not delete) https://github.com/bcgov/design-system/blob/master/styles/colours/colourpalette.md
 > (do not delete) devhub page: /Colour-Palette

## Devhub Content Issue
Is #494949 still the correct colour for text? Gov uses #313132 for its headings and paragraphs.

David

**Comment by dlevineBC** [comment]
Yup #313132 is the new text colour - will update that
