### ISSUE TITLE
Devhub Issue: Prototype with the Design System [XD file not linked]

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/design-system#251]
> path: (do not delete) https://github.com/bcgov/design-system/blob/master/components/about/prototyping_tools.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Design-System/Prototype-with-the-Design-System

## Devhub Content Issue

Text says, "Download XD File", but there is no link.

Also, "member" is misspelled.

Thanks!

**Comment by ty2k** [comment]
Fixed in #252 and now [in production](https://developer.gov.bc.ca/Design-System/Prototype-with-the-Design-System) after a DevHub re-build. Thanks again Mark!
