### ISSUE TITLE
Special Character Macron in BC Sans

### ISSUE THREAD

**Issue by arturwilman** [bcgov/design-system#259]
We have a requirement from a client to have Special Characters to work within the Character Map for BC Sans Unicode Value.
Unicode is 0331

Currently we are using Arial to allow for the Macron G g for the Nisga Act.

**Comment by dlevineBC** [comment]
BC Sans has U+0331 in the character set. This is a combining macron below. When a "g" is typed after it, the character renders as g with macron below. I've tested this on my local machine and using the inspector tool on the gov.bc.ca website. Have you found a bug when trying to use this or is this just a question?

**Comment by arturwilman** [comment]
We have tried to use the BC Sans Unicode but it does not work.

**Comment by arturwilman** [comment]
There is a bug or it is not supported.

**Comment by dlevineBC** [comment]
Can you provide some more detail on how you are inputting the character? There can sometimes be different ways that a font is programmed with combining characters

**Comment by arturwilman** [comment]
Can you provide a working copy? We have an example but no way to serve it up to you. We implemented with a temp fix Arial for for the Macron.

We can send a zip VIA google drive or FTP?

**Comment by arturwilman** [comment]
We were able to get it to work locally but not served up.

**Comment by dlevineBC** [comment]
can you please email me at davis.levine@gov.bc.ca so I can get more details
