### ISSUE TITLE
Devhub Issue: Typography [short description here]

### ISSUE THREAD

**Issue by roopeyds** [bcgov/design-system#263]
> path: (do not delete) https://github.com/bcgov/design-system/blob/master/styles/typography/typography.md
 > (do not delete) devhub page: /Typography

## Devhub Content Issue

Are there plans to support more font weights in BC Sans? Is this in progress? 

Just Bold and Regular can be slightly limiting.

**Comment by dlevineBC** [comment]
We only have plans to support bold and regular at this time. This is primarily due to performance having to load additional weights. Light versions of fonts should be avoided for accessibility.
