### ISSUE TITLE
Devhub Issue: Typography guidance on how to mitigate performance impact of including BC Sans in a web page

### ISSUE THREAD

**Issue by allanhaggett** [bcgov/design-system#270]
> path: (do not delete) https://github.com/bcgov/design-system/blob/master/styles/typography/typography.md
 > (do not delete) devhub page: undefined

## Devhub Content Issue

Hello!
I am being told that I _must_ use BC Sans as the font on the web pages that I am building and being referred to this page to support that. While I like BC Sans and would like to use it in the prescribed manner, I am concerned about the performance impact that including the font necessarily entails. If I simply implement the font as described on this page, my Lighthouse performance scores go from high-90s to low-60s in some cases. 

To illustrate:

An application with BC Sans as implemented in the [BC Gov Bootstrap 4.3 theme](https://github.com/bcgov/bootstrap-theme):
![image](https://user-images.githubusercontent.com/47408983/143096830-cc4da136-156d-433a-9ab4-e8de4aea80fb.png)

Same page, simply replacing Bootstrap with the official CDN version (no BC Sans):
![image](https://user-images.githubusercontent.com/47408983/143096908-b9a50a1e-2f58-4de8-8c3e-0bed3ff6ede9.png)

A near-20% reduction in performance scoring (it is worse depending on the page) that can be traced (in my testing at least) almost exclusively to BC Sans needing to download and process.

The [front page of gov.bc.ca](https://www2.gov.bc.ca/gov/content/home):
![image](https://user-images.githubusercontent.com/47408983/143103147-9219bad9-a64a-4855-9815-a76058820ecb.png)

An additional 3 seconds for an initial page load, entirely to accommodate BC Sans.

Including custom fonts into web pages is "simple" as outlined in this article. What isn't simple is including a custom font in a way that doesn't seriously impact the performance of that page. Google Fonts employs _so many tricks_ to do what it does in an efficient manner, and there are many articles out there that propose solutions, some more practical than others. It seems that the [font-display CSS attribute](https://web.dev/font-display/) can help, but I am hoping to dig deeper and see if the issue can better balance using a cool font with pages that load quickly.

I consider a 20% decrease in page performance a serious accessibility issue that would potentially mean the difference between a page loading _or not_ for our users. Could this page be updated to include some more guidance on how to implement BC Sans while mitigating (at least some of) the performance issue?

Also, I am strongly advocating in my projects that we simply use [the system font stack](https://css-tricks.com/snippets/css/system-font-stack/). Of course the graphic designers are horrified by the concept, but a 100% performance score is tough to argue with. This document states that BC Sans is "the standard font for B.C. Government digital services." Does this mean that we **have** to use it, performance impact or not?

Thank you! Apologies if this is the wrong place to post this.

**Comment by ty2k** [comment]
Hey @allanhaggett, thanks for submitting this issue. Totally agree that we should add something to the Typography page for loading strategies. My understanding is that yes, we do have to use BC Sans for all BC Gov web properties. There is some additional context for the font on the Visual Identity Program's [BC Sans Typeface page](https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/bc-sans).

Like you mention, cloud solutions like Google Fonts pull out all the stops to cut down load times. A Gov-approved, auto-magic CDN link might be the ideal thing for the majority of people, but we don't have an option like that. I imagine the next best thing we could do is provide documentation on some different font loading strategies ([FOUT, FOIT, FOFT](https://css-tricks.com/fout-foit-foft/) or [something else](https://www.zachleat.com/web/comprehensive-webfonts/)). 

I'm no font expert, and I'm wide open to suggestions from the community on which strategies should be included.

**Comment by allanhaggett** [comment]
Apologies for the delayed response :) Thank you very much for the reply! I will continue to research this when I can, and will attempt to provide some guidance myself, perhaps opening a PR here if I can gather something coherent that would be useful.

I'm curious if there is some process to review or otherwise engage with the people who have made this decision that we must use a thing that has fairly serious negative side effects. I would be interested to know if this performance issue was considered, and whether or not we might come up with a solution that less-technical folx could implement; having a Gov-approved CDN available for common assets like this would be amazing!!
