### ISSUE TITLE
Devhub Issue: Typography [short description here]

### ISSUE THREAD

**Issue by Fjiao2023** [bcgov/design-system#273]
> path: (do not delete) https://github.com/bcgov/design-system/blob/master/styles/typography/typography.md
 > (do not delete) devhub page: undefined

## Devhub Content Issue

Hi,

this is for project team of BC Sans Font.  I'm looking for the right contact regarding the Database setup in  order to store the BC SANS font.  my contact info is  Frank.jiao@gov.bc.ca.  your response is appreciated.

Thanks !

Frank Jiao

**Comment by ty2k** [comment]
Hey @Fjiao2023, I'm not sure where to best direct you. This repository holds the content for the [Design System pages on DevHub](https://developer.gov.bc.ca/Design-System/About-the-Design-System), which contains the [Typography guidance](https://developer.gov.bc.ca/Design-System/Typography) referenced in your issue. There is a separate repository for the [BC Sans npm package](https://github.com/bcgov/bc-sans), which is how many software projects use the font. There is not currently a content delivery network version of the font to link to, so it's typical for each software project to distribute its own copy of the font in its front-end.

Feel free to reach out to me on Teams or by email (Tyler.Krys@gov.bc.ca) if I can assist further.
