### ISSUE TITLE
Text Input

### ISSUE THREAD

**Issue by bl-smith** [bcgov/design-system#30]
Evaluation Criteria
•    Impact on citizens: The component will enhance the functionality or usability of B.C. government websites or applications.
•    Usage: The component is commonly used or required and this need cannot be met with an existing component.
•    Volume of Requests: The component has been frequently requested by the community.
## What
> Give a brief description of the style, component or pattern you want to propose.

## Why
> Explain why you think this should be added to the BC Gov Design System.
>
> - What evidence do you have that it's needed by multiple services across government?
> - What evidence do you have that it meets the needs of the users of those services?
> - Have you checked that it doesn't already exist in the BC Gov Design System?

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

**Comment by dlevineBC** [comment]
@orinevares I was messing around with different greys for input borders instead of the blue so we don't conflict in styling with the secondary button - referencing the developers guide of pre-approved grays I would say #8a9198 would be a good option. It passes the WCAG AA contrast standard. The label still has more contrast so the two elements are competing visually. When we get into darker greys it becomes visually overwhelming 
<img width="289" alt="gray-border" src="https://user-images.githubusercontent.com/29607430/54850595-c382fd80-4ca4-11e9-90a4-3ac463650d37.png">

**Comment by orinevares** [comment]
@dlevineBC great! Do you think there could be too much visual noise having the text and text input borders different colours on a larger more complex form?

**Comment by orinevares** [comment]
I can update the components on GitHub, we can also add this grey to the colour palette

**Comment by dlevineBC** [comment]
I think it's less about different colours and what the visual relationship/hierarchy is. If you have the input borders at a higher contrast than the text, the labels become overpowered. You want users to focus more on the label than the box.

**Comment by orinevares** [comment]
Ok makes sense, I'll start on the content updates now.

**Comment by dlevineBC** [comment]
@orinevares Oversight on the contrast check! The previous gray (#8a9198) passes on white background, but there is common usage that text inputs are found on light gray backgrounds (IDIR login), which fails with the #8A9198 . Would recommend this darker gray from the approved palette. #616265

<img width="299" alt="dark-gray" src="https://user-images.githubusercontent.com/29607430/54953714-21625000-4f06-11e9-8428-81464b1bb2ca.png">

**Comment by dlevineBC** [comment]
Actually it still feels a bit dark, the label text in the above image isn't the proper text colour so it's not an accurate example

**Comment by dlevineBC** [comment]
Current UI design for text input - I think the border is a little too thick and the balance between text and border isn't balanced
<img width="303" alt="Screen Shot 2020-04-09 at 9 47 34 AM" src="https://user-images.githubusercontent.com/29607430/78919746-35142200-7a47-11ea-96b1-b1e3ed33d66c.png">


Proposal of change
Recommend to reduce border from 2px to 1px, and reduce the border radius from 4px to 2px. Buttons are currently at 4px radius and I think it's important to keep separation visually between these elements. Border colour should stay the same for contrast requirements
<img width="303" alt="Screen Shot 2020-04-09 at 9 46 59 AM" src="https://user-images.githubusercontent.com/29607430/78919773-3f362080-7a47-11ea-8f05-031780729367.png">

**Comment by davidedwardclark** [comment]
Keeping buttons at 4px radius and reducing input radius to differentiate them makes sense 👍 

I kind of lean towards preferring 2px border myself - but don't feel strongly about this. Be nice to see what a page looks like with a few input boxes on them just to get a feel for what a page would look like with this change. Quickly did up two versions to compare contrast.

![OLD: 2px-border_2px-radius](https://user-images.githubusercontent.com/1013637/78928188-069d4380-7a55-11ea-84d0-8da1196993c7.png)

![NEW: 1px-border_1px](https://user-images.githubusercontent.com/1013637/78928173-01d88f80-7a55-11ea-9b6a-4d9fb5961c3c.png)

**Comment by davidedwardclark** [comment]
^ I don't mind 1px border. We may need to lighten up the down arrow in the Drop Down field if we go with 1px border though.

@dlevineBC Should input labels be bold or regular?

**Comment by davidcusack** [comment]
I like the 2px border as well.

David Cusack
User Experience Design Lead / Web Team Manager
Stakeholder Relations / Ministry of Education
778-679-2382 / david.cusack@gov.bc.ca

**Comment by dlevineBC** [comment]
Assumption to stick with 2px border radius to differentiate button - here is comparison of text inputs on a real form that was just created. So this is a representation of how it could possibly look in the wild. I think the 2px border is just too heavy. It loses the feeling of being an input and it's more of box. Bold text shows more hierarchy between the elements, but more visually balanced at a normal weight.

1px border - font normal
<img width="746" alt="Screen Shot 2020-04-09 at 1 36 22 PM" src="https://user-images.githubusercontent.com/29607430/78938617-5edd4100-7a67-11ea-9854-d0992f3345ac.png">
1px border - font bold
<img width="746" alt="Screen Shot 2020-04-09 at 1 36 44 PM" src="https://user-images.githubusercontent.com/29607430/78938622-5f75d780-7a67-11ea-80e4-57961b0230c8.png">
2px border - font bold
<img width="746" alt="Screen Shot 2020-04-09 at 1 37 14 PM" src="https://user-images.githubusercontent.com/29607430/78938624-600e6e00-7a67-11ea-84f6-2fa49eabc3da.png">
2px border - font normal
<img width="746" alt="Screen Shot 2020-04-09 at 1 37 34 PM" src="https://user-images.githubusercontent.com/29607430/78938625-60a70480-7a67-11ea-951c-641a078579f5.png">

**Comment by davidcusack** [comment]
1px does feel a little less busy.

I don’t really like the bolding. If you are using groups on a form, the group title is usually bolded. Also if everything is bolded then if becomes hard to make text stand out. Say you want to bold a submission date about the form it won’t stand out as much if everything else is bolded.

David Cusack
User Experience Design Lead / Web Team Manager
Stakeholder Relations / Ministry of Education
778-679-2382 / david.cusack@gov.bc.ca

**Comment by davidedwardclark** [comment]
@dlevineBC I prefer option 1, or option 4. I still lean towards 2px border, but i do not feel strongly, and if you feel 1px is better than go for it.

@davidcusack good point about bolding. probably best to go with normal font weight for labels so headings and form group labels stand out more.

**Comment by davidedwardclark** [comment]
The benefit of going 1px input borders is that you differentiate from secondary button styles which is nice.
