### ISSUE TITLE
Refactor components to use 3.0.0 tokens

### ISSUE THREAD

**Issue by mkernohanbc** [bcgov/design-system#313]
Changes to design token structure in 3.0.0-rc1 break existing components built using 2.0.1 tokens.

**Comment by ty2k** [comment]
- [x] Button https://github.com/bcgov/design-system/pull/317

**Comment by ty2k** [comment]
- [x] Select https://github.com/bcgov/design-system/pull/318
- [x] Tag/TagGroup https://github.com/bcgov/design-system/pull/319
- [ ] Tooltip https://github.com/bcgov/design-system/pull/320

**Comment by mkernohanbc** [comment]
Closed by #325 and #406.
