### ISSUE TITLE
Consider changing sizing/spacing units to rem instead of px

### ISSUE THREAD

**Issue by mkernohanbc** [bcgov/design-system#329]
Question from a colleague at WLRS:

> Our team is currently starting our development process using the tokens npm package. After some discussion with our devs, we recognized that we are using rem for text sizes, but use px values for margin+padding instead of em/rem. Was there a rationale around that decision that I could pass along?

In both 2.0.1 and 3.0.0-rc1 of the tokens package, we use `rem` as the unit of measurement for typography tokens, but `px` for sizing and spacing measures.

Before rolling out 3.0.0, can we please evaluate/regroup on:

- Why we made this choice to use separate units in the first place
- What best practice is here (particularly from dev perspective)
- What the impact (eg. to existing components) of changing all units to `rem` would be

**Comment by Philip-Cheung** [comment]
Changed values to rem in both Figma + TS

**Comment by mkernohanbc** [comment]
Thanks @Philip-Cheung. 

Flag for @ty2k: this change feels like it could have knock-on effect on #313 — maybe something to keep an eye on, and confirm that it doesn't create any unexpected gremlins in components we've already built.
