### ISSUE TITLE
Add token and accompanying style for H6

### ISSUE THREAD

**Issue by mkernohanbc** [bcgov/design-system#330]
Flagging a question raised by @ty2k during content review:

> Not specific to this content, but is there any reason we don’t have a token for H6 headings?

Even if H6 is seldom used in practice, it's part of the HTML standard. For the sake of completeness, can we add a style for H6 to the tokens package, please? It's likely an edge case, but seems likely _someone's_ going to need it.

**Comment by Philip-Cheung** [comment]
done

**Comment by Philip-Cheung** [comment]
added h6 to main file + TS
