### ISSUE TITLE
Investigate whether we should include or remove typography.color.placeholder

### ISSUE THREAD

**Issue by mkernohanbc** [bcgov/design-system#332]
Flag from Ali during content review:

> typography.color.placeholder – does this mean ghost text? If this is the case, we need to remove this. Forms should not have any text that disappears. It’s an accessibility thing. Placeholder text was an older understanding of accessibility, but in general any assistance text should be persistent and not disappear.

In general, we should not be endorsing/enabling patterns that have known usability or accessibility issues. Let's discuss the rationale for including this (both in tokens schema and how we do this in components), and whether we remove it entirely or clarify intended/appropriate usage.

See also:

- https://www.nngroup.com/articles/form-design-placeholders
- https://www.w3.org/WAI/WCAG22/Understanding/on-input
- https://www.w3.org/WAI/tutorials/forms/instructions/

**Comment by Philip-Cheung** [comment]
If we remove that placeholder token, we'd have to axe all placeholder text in every component. I feel a bit uneasy about this as literally all components in established DS have placeholder text for inputs/datepickers/etc

**Comment by mkernohanbc** [comment]
Okay, let's leave the token as is. I think you're right that there are potentially legitimate use-cases, and we can guide people in the right direction in docs. I think Ali's larger point that we should be modelling best practice is valid, and something we should discuss in context of individual components.
