### ISSUE TITLE
Angular example

### ISSUE THREAD

**Issue by datasmithtechgrp** [bcgov/design-system#382]
### Related component

all

### Description

I am looking for an angular example as to how to use this font package

### Rationale

Currently developing an angular application

### Additional information

tbd

**Comment by ty2k** [comment]
Hey @datasmithtechgrp , thanks for the question.

There is a specific repository for the BC Sans npm package here: [bcgov/bc-sans](https://github.com/bcgov/bc-sans)

Check out the [React example in the README](https://github.com/bcgov/bc-sans/tree/master?tab=readme-ov-file#react) there to see how you might use it.

There isn't an Angular-specific example in that repo's README at the moment. I'm not sure what the best practice is with that framework these days, but I would try importing the CSS file from that package into the root of your app to see if it "just works": `import '@bcgov/bc-sans/css/BC_Sans.css';`. Then, reference `BC Sans` as your `font-family` in a CSS rule for some component.

If that doesn't work, you can make it work yourself by serving the font files from that repo and referencing them how you please:

1. Serve the font files yourself at whatever path you like.
2. Use [the CSS for the `@font-face` declarations](https://github.com/bcgov/bc-sans/blob/master/css/BC_Sans.css) from the bcgov/bc-sans package, but update the font path references (`url(<your file path here>)`) to point to where your app is serving them. Position this CSS import at a spot in your app where it will load ahead of component-specific files that need it.
3. In your component styles, you should be able to reference the `BC Sans` font name:

```css
* {
  font-family: "BC Sans";
}
```
