### ISSUE TITLE
Fix mismatched borderRadius token name between Figma and npm

### ISSUE THREAD

**Issue by mkernohanbc** [bcgov/design-system#386]
We have a mismatch between our Figma library and our code library in the name of this token:

- Figma: `layout.borderRadius.default`
- CSS: `--layout-border-radius-medium`

The final part of the token name was changed from `medium` to `default` in 3.0.0, based on feedback from user testing that suggested people were instinctively looking for a 'correct', 'standard' value.

Best guess at what happened here is that that change happened in Figma after the Tokens Studio export used to create the 3.0.0 npm build. The value is set to `medium` in the tokens.json output file: https://github.com/ty2k/design-system/blob/1f81f09aefe592bf9531f2419ca7865e3c2e6b64/packages/design-tokens/input/tokens.json#L461

In the next release of the design tokens package, we need to re-match these two tokens. We have two options:

- Change CSS/JS token to `default`: breaking change
- Revert Figma token to `medium` and provide clarity another way (eg. through token descriptions - see #350)

**Comment by Philip-Cheung** [comment]
The easiest thing to do is to revert it back to medium. I won't be able to do it on TS because of that github link credentials bug. In the meantime I can add a description on the token to say medium is the default radius.
