### ISSUE TITLE
Inline alert - Figma component

### ISSUE THREAD

**Issue by mkernohanbc** [bcgov/design-system#435]
The inline alert component provides a method to display important information within an interface. It is a visually distinctive block that renders inline (usually spanning the full width of its container.) It is not an interruptive element like a modal dialog.

Inline alerts may:

- Load on render to highlight important information for all users (eg. a status message for all users of a product)
- Render dynamically based on user action, to highlight a context-specific notice or issue (eg. an error message)

It has functional overlap with callouts and modal dialogs.

The component requires visual themes for 4 different contexts/states:

- Generic/default informational state
- Success or confirmation state
- Warning state
- Error/danger state

It should also support the addition of additional components (usually buttons), and optionally be closeable by the user.

**Comment by mkernohanbc** [comment]
@Philip-Cheung back-filled a sketch of the requirements for this component for reference. I've started working on an implementation of the current design in #433, but holding for now — can you please confirm whether that spec is final, or if you want to do another pass on the Figma component?

**Comment by Philip-Cheung** [comment]
> [@Philip-Cheung](https://github.com/Philip-Cheung) back-filled a sketch of the requirements for this component for reference. I've started working on an implementation of the current design in [#433](https://github.com/bcgov/design-system/issues/433), but holding for now — can you please confirm whether that spec is final, or if you want to do another pass on the Figma component?

The design is final
