### ISSUE TITLE
Some typography design tokens don't work

### ISSUE THREAD

**Issue by duncan-oxd** [bcgov/design-system#502]
### Component

Design tokens

### Description

Some of the CSS variables provided by the design tokens package use the `font` shorthand property, for example:

```css
  --typography-regular-h6: 400 1.125rem/1.913rem 'BC Sans'; /* Alternate (unbolded) style for Heading 6 */
```

But browsers can't use a single variable for shorthand properties (apparently 🤷).

You'd need to define the font weight, size, and family either as separate properties, or at least separate variables to combine on one line with spaces. I created a codepen to see for myself that demonstrates this: https://codepen.io/oxd_duncan/pen/rNXgXmp

Additionally, the design tokens [Glossary page](https://www2.gov.bc.ca/gov/content/digital/design-system/foundations/design-tokens/glossary) shows the values for these variables as just the size value:

![Image](https://github.com/user-attachments/assets/83f05c60-744f-4ae1-b37f-5a56b061fc92)

And if you used that variable in the `font-size` property, it wouldn't work either.

### Steps to reproduce

Define a style using one of the variables that combines several font properties into a shorthand:

```html
<p>Foo</p>
```

```css
p { font: var(--typography-regular-h6) }
```

This won't render with the right size/weight/etc defined in the variable.

### Technical information

Affects the latest Chrome and Firefox on MacOS, but likely everywhere because I think the behavior is an intentional part of the CSS spec.

**Comment by ty2k** [comment]
Hey @duncan-oxd, do the composite/shorthand tokens like `--typography-regular-h6` work the way you expect if you terminate the CSS rules with a semicolon? I find that the code in your Codepen works for me in both Firefox and Chrome if I add a `;` to the end of line 6 in the CSS:

![Chrome example](https://github.com/user-attachments/assets/bac6adc7-0c1a-4410-814b-c31b9010100f)
![Firefox example](https://github.com/user-attachments/assets/9b56ca17-b57c-44bf-a1f7-dd747ef7e914)

If that doesn't fix it, here are some other things to check:
- Are you importing the prefixed versions of the tokens (`--bcds-typography-regular-h6`) but writing CSS rules with the non-prefixed version (`--typography-regular-h6`)? We include both in case folks are using existing tokens/variables from somewhere else and they want names with the extra `bcds` to help avoid name collisions. 
- Is BC Sans working in general? Note that the tokens target the name `BC Sans` with a space (like what the font itself has in its metadata) as opposed to `BCSans` without a space. The [npm package for the font](https://www.npmjs.com/package/@bcgov/bc-sans) includes stylesheets for both for backwards compatibility, but we fixed the name prior to releasing the design tokens library.

**Comment by duncan-oxd** [comment]
Sorry, @ty2k , I was misinterpreting what I saw in devtools, and then I only confused myself more with that typo in my codepen.

**Comment by ty2k** [comment]
@duncan-oxd No worries, glad it's working! :)
