### ISSUE TITLE
Secondary Button

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#54]
## What
> A secondary button is a supporting call to action

## Why
> Pages will sometimes have more than one action that a user can do. There should not more more than one primary button per page so a secondary button style is needed.

**Comment by orinevares** [comment]
Australia

Primary Button
![image](https://user-images.githubusercontent.com/43620986/54840143-89f0c900-4c89-11e9-9b8d-08ede40d07bb.png)


Secondary Button
![image](https://user-images.githubusercontent.com/43620986/54840107-747b9f00-4c89-11e9-8e7c-fff8fe68dab6.png)

![image](https://user-images.githubusercontent.com/43620986/54840146-8cebb980-4c89-11e9-95a7-f5d4308a3472.png)

**Comment by orinevares** [comment]
US Design System

![image](https://user-images.githubusercontent.com/43620986/54840161-95dc8b00-4c89-11e9-92e2-eea45c588796.png)

**Comment by orinevares** [comment]
BC Gov FOI Application

![image](https://user-images.githubusercontent.com/43620986/54840192-a987f180-4c89-11e9-871d-901edec1a11e.png)

![image](https://user-images.githubusercontent.com/43620986/54840201-ad1b7880-4c89-11e9-8486-6ef35e3f7f83.png)

**Comment by orinevares** [comment]
MSP Application

![image](https://user-images.githubusercontent.com/43620986/54840214-b86ea400-4c89-11e9-8553-ff158197aa6b.png)
![image](https://user-images.githubusercontent.com/43620986/54840218-ba386780-4c89-11e9-8761-eee15e081ed3.png)

**Comment by orinevares** [comment]
Onestop

![image](https://user-images.githubusercontent.com/43620986/54840240-cc1a0a80-4c89-11e9-95c1-45975e88e4c9.png)

**Comment by orinevares** [comment]
Cannabis

![image](https://user-images.githubusercontent.com/43620986/54840279-de944400-4c89-11e9-87ae-6997ed37d57a.png)

![image](https://user-images.githubusercontent.com/43620986/54840286-e05e0780-4c89-11e9-8e60-b3434170aac2.png)

**Comment by orinevares** [comment]
BCEID

![image](https://user-images.githubusercontent.com/43620986/54840292-e6ec7f00-4c89-11e9-98da-bafa5f648286.png)

![image](https://user-images.githubusercontent.com/43620986/54840297-e94ed900-4c89-11e9-9ba8-a460a27a5da8.png)

**Comment by orinevares** [comment]
Some Initial concepts for the BC Gov version.

![image](https://user-images.githubusercontent.com/43620986/54840634-a93c2600-4c8a-11e9-8fbe-14a23df1ae27.png)

**Comment by orinevares** [comment]
Leaning towards the middle ghost style design for the following reasons.

What is the problem?
Currently secondary buttons are inconsistent and can be confusing for users. Often their colours are more prominent than the primary button. Additionally, they are often too small and do not meet accessibility standards.

What are the contraints?
The button must match the branding of BC Gov properties, support accessibility considerations, convey a secondary action by colour and prominence, and can appear anywhere in the body of a digital interface.

What is our proposed solution?
A ghost style secondary button which copies the basic properties of the primary button.

How did we come to this solution?
• The outlines and colours match that of a primary button and the BC Gov colour palette.
• The lack of fill puts the button into the background and attracts less attention from the primary button.
• This matches the UI design of MacOS and Microsoft increasing the learnability for users.
• The rectangular shape resembles the primary button and conveys similar interactivity.
• The size maintains a minimum of 44px by 44px
• The text underlines and opacity changes on hover to provide multiple ways to convey information

**Comment by dlevineBC** [comment]
From the Environmental Assessment Office application. They are currently using this pattern. Things to note. On hover it has a complete fill. On the dark background the hover changes to yellow rather than white.

Left: Normal state / Right: onHover
<img width="270" alt="background" src="https://user-images.githubusercontent.com/29607430/55025636-95f8c580-4fbe-11e9-91d5-9e7b6a240eac.png">
<img width="241" alt="ghost-hover" src="https://user-images.githubusercontent.com/29607430/55025637-95f8c580-4fbe-11e9-9c08-7bb45e5d72a5.png">
