### ISSUE TITLE
Design System components organized hierarchically for side navigation

### ISSUE THREAD

**Issue by orinevares** [bcgov/design-system#61]
![Screen Shot 2019-01-15 at 3.22.47 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/4bbf90de-d034-4c07-834a-882a3a699056)

**Comment by patricksimonian** [comment]
since we don't have the **parent category** yet. Can we sort these alphabetically in place for now? Perhaps work on that as a seperate issue?

**Comment by orinevares** [comment]
@patricksimonian yes that would be great for now. Whatever you have the capacity to do moving this forward. I'll split up the issue into two now.

**Comment by patricksimonian** [comment]
work around provided, this task was completed in the devhub-app-web repo.
